import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    # User resources
    cutout="<resources>/user/cutouts/{cutout}.nc",
    tech_specs="<resources>/user/tech_specs/{tech}.yaml",
    layout_raster="<resources>/user/layouts_raster/{layout}.tif",
    layout_point="<resources>/user/layouts_point/{layout}.csv",
    shapes="<resources>/user/shapes/{shape}.parquet",
    # Module results
    capacity_factors="<results>/cutouts/{cutout}/shapes/{shape}/layouts_{layout_type}/{layout}/capacityfactors_{tech}.nc",
    capacity_factors_mean="<results>/cutouts/{cutout}/shapes/{shape}/layouts_{layout_type}/{layout}/capacityfactors_{tech}_mean.nc",
    matrix="<results>/cutouts/{cutout}/shapes/{shape}/layouts_{layout_type}/{layout}/capacityfactors_{tech}_matrix.nc",
    plot="<results>/cutouts/{cutout}/shapes/{shape}/layouts_{layout_type}/{layout}/capacityfactors_map_{tech}.png",

# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


wildcard_constraints:
    layout_type="raster|point",

# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)

# Load python files in scripts that are used in other scripts, but not run itself.
# This is necessary for integrating the snakemake module via reference to GitHub.
workflow.source_path("scripts/_backend_atlite/_aggregate_point_layout.py")
workflow.source_path("scripts/_backend_atlite/_aggregate_raster_layout.py")
workflow.source_path("scripts/_plots.py")
workflow.source_path("scripts/_schemas.py")


# Add all your includes here.
include: "rules/automatic.smk"
include: "rules/capacity_factors.smk"


rule all:
    message:
        "ERROR: Invalid `rule all:` call"
    default_target: True
    output:
        "INVALID",
    log:
        stderr="logs/all.stderr",
    conda:
        "envs/shell.yaml"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
