$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
required:
  - download_cutout
  - backend
  - aggregate
additionalProperties: false

properties:
  download_cutout:
    type: boolean
    default: false
    description: "Whether to download the cutout automatically or use a user-provided one."
  backend:
    type: string
    enum: ["atlite"]
    description: "The backend to use for the module."
  aggregate:
    type: boolean
    description: "Whether to aggregate the data to shapes or not."
  # if download_cutout is True, need to provide these parameters, which are used to download the cutout
  cutout_params:
    type: object
    required:
      - module
      - x
      - y
      - time
    additionalProperties: false
    properties:
      module:
        type: string
        enum: ["era5"]
        description: "The module to use for downloading the cutout."
      x:
        type: array
        items:
          type: number
        description: "Longitude coordinates for the cutout."
      y:
        type: array
        items:
          type: number
        description: "Latitude coordinates for the cutout."
      time:
        type: array
        items:
          type: string
        description: "Time range for the cutout in ISO 8601 format."
      monthly_requests:
        type: boolean
        default: false
        description: "Whether to request data monthly."
