# A minimal example of how to configure this module
download_cutout: True
backend: atlite
layout: raster  # raster or point
aggregate: true
cutout_params:
  module: era5
  x: [-17., 37.]
  y: [32., 72.]
  time: ["2017-01-01", "2017-01-07"]
